"""init

Revision ID: 55e1a405658e
Revises: 045b6e97dc50
Create Date: 2018-09-16 11:19:02.077019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55e1a405658e'
down_revision = '045b6e97dc50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('header', sa.String(length=1000), nullable=True))
    op.drop_column('post', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('title', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    op.drop_column('post', 'header')
    # ### end Alembic commands ###
