"""initial migrate

Revision ID: bd890b3f629e
Revises: 1c7229f48fcf
Create Date: 2018-09-15 15:35:01.054866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd890b3f629e'
down_revision = '1c7229f48fcf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_writer_email', table_name='writer')
    op.drop_index('ix_writer_username', table_name='writer')
    op.drop_table('writer')
    op.add_column('post', sa.Column('title', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'title')
    op.create_table('writer',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('pass_secure', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='writer_pkey')
    )
    op.create_index('ix_writer_username', 'writer', ['username'], unique=False)
    op.create_index('ix_writer_email', 'writer', ['email'], unique=True)
    # ### end Alembic commands ###
